spring:
  mongodb:
    uri: mongodb://algashop-mongodb-1:27017,algashop-mongodb-2:27017,algashop-mongodb-3:27017/product_catalog?replicaSet=rs0

logging:
  level:
    org.mongodb.driver.protocol.command: DEBUG
    org.mongodb.driver.cluster: OFF

algashop:
  data-load:
    enabled: true
    auto-delete: true
